language: python
python: 
- "3.6"

install: 
- "pip install pytest"
- "pip install pytest-cov"
- "pip install -r requirements.txt"
- "pip install coveralls"
script: python -m pytest --cov=api/

after_success:
- coveralls