language: python
python: 
- "3.6"

install: 
- "pip install pytest"
- "pip install pytest-cov"
- "pip install -r requirements.txt"
- "pip install coveralls"
services:
- postgresql

before_script:
- psql -c 'create database stackoverflowliteapi;' -U postgres

script: python -m pytest --cov=api/

after_success:
- coveralls