language: python
python: 
- "3.6"

env:
- DATABASE_URL=postgresql://postgres@localhost:5432/stackoverflowliteapi

install: 
- "pip install pytest"
- "pip install pytest-cov"
- "pip install -r requirements.txt"
- "pip install coveralls"
services:
- postgresql

before_script:
- psql -c 'create database stackoverflowliteapi;' -U postgres
- python migrate.py

script: python -m pytest --cov=api/

after_success:
- coveralls